# Generated by Django 4.2.2 on 2023-06-20 15:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('inactive', 'Неактивно')], default='inactive', max_length=32, verbose_name='Статус')),
                ('grade', models.CharField(choices=[('intern', 'Начинающий'), ('junior', 'Младший специалист'), ('middle', 'Средний специалист'), ('senior', 'Старший специалист')], default='intern', max_length=32, verbose_name='Грэйд')),
                ('specialty', models.CharField(choices=[('qa', 'Тестирование'), ('frontend', 'Front-end'), ('backend', 'Back-end')], default=None, max_length=32, null=True, verbose_name='Специальность')),
                ('salary', models.IntegerField(default=100000, verbose_name='Зарплатные ожидания (руб)')),
                ('education', models.CharField(default=None, max_length=2048, null=True, verbose_name='Образование')),
                ('experience', models.CharField(default=None, max_length=2048, null=True, verbose_name='Профессиональный опыт')),
                ('portfolio', models.CharField(default=None, max_length=2048, null=True, verbose_name='Ссылка на портфолио')),
                ('title', models.CharField(blank=True, default='', max_length=128, verbose_name='Название')),
                ('phone', models.CharField(default=None, max_length=12, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Номер должен быть представлен в международном формате: +79998887766')], verbose_name='Номер телефона')),
                ('email', models.CharField(default=None, max_length=128, null=True, verbose_name='Электронная почта')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
    ]
